on:
  push:
    branches:
      - prod

name: ğŸš€ Deploy system on push

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ§° Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: ğŸ“¦ Install dependencies with Yarn
        run: yarn install --ignore-engines

      - name: ğŸ§¹ Remove old build
        run: rm -rf build # or `dist`, depending on your app

      - name: âš™ï¸ Build the app
        run: DISABLE_ESLINT_PLUGIN=true yarn build

      - name: ğŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: mustaheq.org
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /sawaed/
          local-dir: build # or dist, whichever contains your output
